export type ControlItem = {
  id: number;
  principio: string;
  tactica: string;
  pregunta: string;
  accion: string;
};

export const PRIVOPS: ControlItem[] = [
  { id: 1, principio: "MINIMIZAR", tactica: "Seleccionar", pregunta: "¿Se ha identificado y documentado cuáles son los datos personales estrictamente necesarios para cumplir la finalidad del tratamiento?", accion: "Documentar un inventario de datos mínimos requeridos por proceso. Eliminar campos innecesarios en formularios." },
  { id: 2, principio: "MINIMIZAR", tactica: "Seleccionar", pregunta: "¿Los formularios de captura de datos (físicos y digitales) solicitan únicamente los datos indispensables para la finalidad declarada?", accion: "Revisar todos los formularios y eliminar campos no justificados. Documentar la justificación de cada dato solicitado." },
  { id: 3, principio: "MINIMIZAR", tactica: "Excluir", pregunta: "¿Existe un procedimiento para excluir datos irrelevantes o excesivos de las bases de datos y procesos?", accion: "Crear procedimiento de depuración periódica de datos excesivos." },
  { id: 4, principio: "MINIMIZAR", tactica: "Remover", pregunta: "¿Se eliminan los datos personales cuando ya no son necesarios para los fines del tratamiento?", accion: "Implementar política de retención y eliminación con plazos definidos." },
  { id: 5, principio: "MINIMIZAR", tactica: "Eliminar", pregunta: "¿Se borran los datos personales de manera segura, incluyendo las copias de respaldo (backups)?", accion: "Implementar procedimientos de borrado seguro certificado incluyendo backups." },
  { id: 6, principio: "OCULTAR", tactica: "Restringir", pregunta: "¿Existen controles de acceso (técnicos y organizacionales) que impidan el acceso a datos personales por personas no autorizadas?", accion: "Implementar control de acceso basado en roles (RBAC) y principio de menor privilegio." },
  { id: 7, principio: "OCULTAR", tactica: "Restringir", pregunta: "¿Se aplica el principio de menor privilegio en los accesos a sistemas que procesan datos personales?", accion: "Revisar y ajustar perfiles de acceso. Implementar revisiones periódicas de privilegios." },
  { id: 8, principio: "OCULTAR", tactica: "Ofuscar", pregunta: "¿Se utilizan técnicas de ofuscación o enmascaramiento de datos personales (data masking, cifrado columnar, etc.)?", accion: "Implementar data masking en ambientes de prueba y cifrado en bases de datos productivas." },
  { id: 9, principio: "OCULTAR", tactica: "Ofuscar", pregunta: "¿Los datos personales sensibles (financieros, de salud) se almacenan cifrados en reposo y en tránsito?", accion: "Implementar cifrado AES-256 en reposo y TLS 1.2+ en tránsito para datos sensibles." },
  { id: 10, principio: "OCULTAR", tactica: "Disociar", pregunta: "¿Se implementan técnicas de disociación para romper vínculos entre datos personales y la identidad del titular?", accion: "Evaluar e implementar técnicas de seudonimización o anonimización según el riesgo." },
  { id: 11, principio: "OCULTAR", tactica: "Mezclar", pregunta: "¿Se utilizan técnicas de mezcla o perturbación de datos en ambientes de desarrollo y pruebas?", accion: "Prohibir uso de datos reales en ambientes no productivos. Usar datos sintéticos o enmascarados." },
  { id: 12, principio: "SEPARAR", tactica: "Aislar", pregunta: "¿Los datos personales se almacenan en bases de datos separadas lógica o físicamente según su sensibilidad?", accion: "Segmentar bases de datos por nivel de sensibilidad. Separar datos financieros de datos de contacto." },
  { id: 13, principio: "SEPARAR", tactica: "Aislar", pregunta: "¿Se evita el almacenamiento centralizado excesivo que facilite el perfilamiento de titulares?", accion: "Evaluar arquitectura de datos y separar repositorios para evitar perfilamiento no autorizado." },
  { id: 14, principio: "SEPARAR", tactica: "Distribuir", pregunta: "¿En el caso de arquitectura distribuida, los datos están repartidos de forma que no se concentren bajo una sola entidad?", accion: "Revisar arquitectura y distribuir responsabilidades de custodia de datos." },
  { id: 15, principio: "ABSTRAER", tactica: "Sumarizar", pregunta: "¿Se utilizan datos resumidos o agregados en lugar de datos individuales detallados cuando la finalidad lo permite?", accion: "Usar reportes agregados para análisis. Evitar exposición de datos individuales cuando no es necesario." },
  { id: 16, principio: "ABSTRAER", tactica: "Agrupar", pregunta: "¿Los reportes y análisis trabajan con información agrupada en lugar de datos de cada persona natural?", accion: "Implementar reportes por cohortes o grupos. Configurar dashboards con datos agregados." },
  { id: 17, principio: "ABSTRAER", tactica: "Perturbar", pregunta: "¿Se aplican técnicas de perturbación o privacidad diferencial para proteger datos en análisis?", accion: "Evaluar implementación de privacidad diferencial en modelos analíticos y de riesgo." },
  { id: 18, principio: "INFORMAR", tactica: "Suministrar", pregunta: "¿Se informa de manera clara y transparente a los titulares sobre el tratamiento de sus datos personales?", accion: "Revisar y actualizar avisos de privacidad en todos los canales (web, app, sucursales, contratos)." },
  { id: 19, principio: "INFORMAR", tactica: "Suministrar", pregunta: "¿Los avisos de privacidad están disponibles antes de la recolección de datos y son comprensibles?", accion: "Asegurar que el aviso de privacidad esté visible y en lenguaje claro antes de cualquier recolección." },
  { id: 20, principio: "INFORMAR", tactica: "Explicar", pregunta: "¿Se explican claramente las finalidades del tratamiento y los motivos por los cuales se requieren los datos?", accion: "Documentar finalidades específicas por proceso y comunicarlas al titular." },
  { id: 21, principio: "INFORMAR", tactica: "Notificar", pregunta: "¿Existe un procedimiento para notificar a los titulares cuando sus datos se comparten con terceros?", accion: "Implementar protocolo de notificación para transferencias y cesiones de datos." },
  { id: 22, principio: "INFORMAR", tactica: "Notificar", pregunta: "¿Existe un procedimiento para notificar vulneraciones de seguridad a los titulares conforme a la LOPDP?", accion: "Crear protocolo de notificación de brechas con plazos, canales y contenido mínimo." },
  { id: 23, principio: "CONTROLAR", tactica: "Consentir", pregunta: "¿Se recoge el consentimiento explícito, informado, inequívoco y transparente de los titulares?", accion: "Revisar mecanismos de consentimiento. Asegurar que sean granulares y no precondicionados." },
  { id: 24, principio: "CONTROLAR", tactica: "Consentir", pregunta: "¿El consentimiento es granular (permite aceptar unas finalidades y rechazar otras)?", accion: "Implementar consentimiento por capas y por finalidad específica." },
  { id: 25, principio: "CONTROLAR", tactica: "Escoger", pregunta: "¿Los titulares pueden otorgar un consentimiento libre, sin que esté absolutamente condicionado?", accion: "Eliminar condicionamientos indebidos (ej: no negar un servicio esencial por no consentir fines secundarios)." },
  { id: 26, principio: "CONTROLAR", tactica: "Actualizar", pregunta: "¿Existen mecanismos para que los titulares actualicen o rectifiquen sus datos personales?", accion: "Implementar funcionalidad de autoservicio en canales digitales y presenciales para actualización." },
  { id: 27, principio: "CONTROLAR", tactica: "Retraer", pregunta: "¿Existen mecanismos para ejercer derechos de oposición, suspensión, eliminación y portabilidad?", accion: "Implementar portal o canal de atención para ejercicio de derechos ARCO+ con seguimiento y plazos." },
  { id: 28, principio: "CONTROLAR", tactica: "Retraer", pregunta: "¿Los mecanismos de ejercicio de derechos son accesibles (web, correo electrónico, chat, presencial)?", accion: "Ofrecer al menos 2 canales accesibles para ejercicio de derechos. Documentar tiempos de respuesta." },
  { id: 29, principio: "CUMPLIR", tactica: "Responsabilizar", pregunta: "¿La protección de datos personales está alineada con las estrategias y objetivos institucionales?", accion: "Incluir protección de datos en la estrategia institucional y plan operativo anual." },
  { id: 30, principio: "CUMPLIR", tactica: "Responsabilizar", pregunta: "¿Existe una política institucional de protección de datos personales aprobada por la alta dirección?", accion: "Aprobar y difundir política de protección de datos firmada por la máxima autoridad." },
  { id: 31, principio: "CUMPLIR", tactica: "Mantener", pregunta: "¿Se mantiene una declaración de aplicabilidad con las medidas de seguridad jurídicas, organizacionales y técnicas?", accion: "Elaborar y mantener actualizada la declaración de aplicabilidad de controles." },
  { id: 32, principio: "CUMPLIR", tactica: "Mantener", pregunta: "¿Se ha designado personal especializado para la implementación de controles de protección de datos?", accion: "Designar formalmente Delegado de Protección de Datos y equipo de apoyo." },
  { id: 33, principio: "CUMPLIR", tactica: "Monitorear", pregunta: "¿Se audita la eficacia y eficiencia de los controles de riesgo implementados?", accion: "Programar auditorías internas periódicas (al menos anuales) sobre controles de protección de datos." },
  { id: 34, principio: "DEMOSTRAR", tactica: "Registrar", pregunta: "¿Se documentan todos los procesos decisionales y se mantiene un Registro de Actividades de Tratamiento (RAT)?", accion: "Crear y mantener RAT actualizado conforme a la LOPDP para cada actividad de tratamiento." },
  { id: 35, principio: "DEMOSTRAR", tactica: "Auditar", pregunta: "¿Se verifican periódicamente la actualización, autenticidad e integridad de los registros de tratamiento?", accion: "Establecer calendario de verificación trimestral del RAT y registros asociados." },
  { id: 36, principio: "DEMOSTRAR", tactica: "Auditar", pregunta: "¿Se registran y revisan los incidentes de seguridad ocurridos en un periodo determinado?", accion: "Implementar registro de incidentes con análisis de causa raíz y lecciones aprendidas." },
  { id: 37, principio: "DEMOSTRAR", tactica: "Reportar", pregunta: "¿Se guardan los eventos de manera confidencial y se pueden presentar a la SPDP cuando sean requeridos?", accion: "Mantener archivo seguro de evidencias listo para presentar ante requerimiento de la SPDP." },
];

export const SECOPS: ControlItem[] = [
  { id: 1, principio: "INTEGRACIÓN", tactica: "Diseño seguro", pregunta: "¿Se incorporan requisitos de seguridad y protección de datos desde la fase de diseño de nuevos sistemas o funcionalidades?", accion: "Incluir checklist de seguridad y privacidad en el proceso de diseño de requerimientos." },
  { id: 2, principio: "INTEGRACIÓN", tactica: "Diseño seguro", pregunta: "¿Se implementa cifrado, autenticación robusta y minimización de datos desde el inicio del desarrollo?", accion: "Definir estándares de cifrado y autenticación como requisitos no funcionales obligatorios." },
  { id: 3, principio: "INTEGRACIÓN", tactica: "Revisión código", pregunta: "¿Se realizan revisiones de código enfocadas en seguridad y protección de datos antes del despliegue?", accion: "Implementar revisiones de código con checklist de seguridad y privacidad." },
  { id: 4, principio: "AUTOMATIZACIÓN", tactica: "SAST", pregunta: "¿Se realizan análisis estáticos de seguridad del código fuente (SAST) para detectar vulnerabilidades?", accion: "Integrar herramienta SAST en el pipeline CI/CD para análisis automático de código." },
  { id: 5, principio: "AUTOMATIZACIÓN", tactica: "DAST", pregunta: "¿Se realizan análisis dinámicos de seguridad de aplicaciones en ejecución (DAST)?", accion: "Implementar pruebas DAST periódicas para detectar inyecciones SQL, XSS y exposición de datos." },
  { id: 6, principio: "AUTOMATIZACIÓN", tactica: "SCA", pregunta: "¿Se analizan los componentes de terceros y librerías para detectar vulnerabilidades conocidas (SCA)?", accion: "Implementar análisis de composición de software para verificar librerías de cifrado y sesiones." },
  { id: 7, principio: "AUTOMATIZACIÓN", tactica: "IaC", pregunta: "¿Se escanea la infraestructura como código para verificar configuraciones seguras?", accion: "Revisar configuraciones de bases de datos, almacenamiento y redes para evitar exposición pública." },
  { id: 8, principio: "AUTOMATIZACIÓN", tactica: "Fuga de datos", pregunta: "¿Se realizan escaneos automatizados para detectar exposición de tokens, contraseñas o datos personales en código?", accion: "Integrar detección de secretos y datos sensibles en el pipeline de desarrollo." },
  { id: 9, principio: "AUTOMATIZACIÓN", tactica: "CI/CD", pregunta: "¿El pipeline CI/CD ejecuta automáticamente todas las pruebas de seguridad antes del despliegue a producción?", accion: "Configurar gates de seguridad obligatorios en el pipeline CI/CD." },
  { id: 10, principio: "COLABORACIÓN", tactica: "Equipos integrados", pregunta: "¿Existe colaboración formal entre los equipos de desarrollo, operaciones, seguridad y protección de datos?", accion: "Establecer comité interdisciplinario con reuniones periódicas de revisión." },
  { id: 11, principio: "COLABORACIÓN", tactica: "Validación diseño", pregunta: "¿Se valida desde el diseño que las funcionalidades cumplan con principios de minimización y acceso restringido?", accion: "Incluir al DPO o equipo de privacidad en las revisiones de diseño funcional." },
  { id: 12, principio: "COLABORACIÓN", tactica: "Datos de prueba", pregunta: "¿Los entornos de prueba evitan exponer datos reales sin medidas de control adecuadas?", accion: "Prohibir uso de datos productivos en pruebas. Usar datos sintéticos o enmascarados." },
  { id: 13, principio: "COLABORACIÓN", tactica: "Control acceso", pregunta: "¿Se implementan y monitorean controles de acceso y trazabilidad según la sensibilidad de la información?", accion: "Implementar logging de accesos y alertas para accesos a datos de alta sensibilidad." },
  { id: 14, principio: "MONITOREO", tactica: "Detección", pregunta: "¿Se implementan sistemas de detección de intrusos y monitoreo de registros en tiempo real?", accion: "Implementar IDS/IPS y SIEM con alertas automatizadas para eventos de seguridad." },
  { id: 15, principio: "MONITOREO", tactica: "Alertas", pregunta: "¿Existen alertas automatizadas para comportamientos anómalos y accesos no autorizados a datos personales?", accion: "Configurar alertas para accesos masivos, horarios inusuales y descargas de datos." },
  { id: 16, principio: "MONITOREO", tactica: "Retroalimentación", pregunta: "¿Los hallazgos de monitoreo se retroalimentan para ajustar políticas y configuraciones?", accion: "Establecer proceso formal de lecciones aprendidas y mejora continua de controles." },
  { id: 17, principio: "MONITOREO", tactica: "Trazabilidad", pregunta: "¿Se mantiene trazabilidad completa de accesos y operaciones sobre datos personales?", accion: "Implementar logs de auditoría inmutables con retención mínima conforme a normativa." },
];

export const RISKOPS: ControlItem[] = [
  { id: 1, principio: "GESTIÓN RIESGOS", tactica: "Eval. inicial", pregunta: "¿Se realiza una gestión de riesgos para la protección de derechos y libertades desde la concepción de cada proyecto?", accion: "Implementar evaluación de riesgos de privacidad como paso obligatorio en la gestión de proyectos." },
  { id: 2, principio: "GESTIÓN RIESGOS", tactica: "Escenarios", pregunta: "¿Se elaboran y comparan escenarios de riesgos probables contra los derechos y libertades de los titulares?", accion: "Desarrollar metodología de escenarios de riesgo con impacto en derechos fundamentales." },
  { id: 3, principio: "GESTIÓN RIESGOS", tactica: "EIPD", pregunta: "¿Se realiza la Evaluación de Impacto del Tratamiento de Datos Personales (EIPD) cuando corresponde?", accion: "Ejecutar EIPD para tratamientos de alto riesgo conforme a la Guía de Gestión de Riesgos SPDP." },
  { id: 4, principio: "INTEGRACIÓN SEG.", tactica: "Convergencia", pregunta: "¿Se integran los resultados de la gestión de riesgos de privacidad con la gestión de riesgos de seguridad de la información?", accion: "Crear matriz integrada de riesgos que vincule riesgos de privacidad con riesgos de seguridad." },
  { id: 5, principio: "INTEGRACIÓN SEG.", tactica: "Convergencia", pregunta: "¿Las operaciones DevPrivOps se integran con las DevSecOps para mitigar riesgos desde la concepción del proyecto?", accion: "Establecer flujo de trabajo integrado entre equipos de privacidad y seguridad." },
  { id: 6, principio: "ESTÁNDARES", tactica: "Marcos referencia", pregunta: "¿Se utilizan estándares y guías reconocidas para las operaciones de privacidad y seguridad (ISO 27001, ISO 27701, NIST, etc.)?", accion: "Adoptar al menos un marco de referencia internacional. Documentar su aplicación." },
  { id: 7, principio: "ESTÁNDARES", tactica: "Métricas", pregunta: "¿Se utilizan métricas significativas y modelos de riesgo adecuados para reducir la incertidumbre?", accion: "Definir KPIs de protección de datos y reportarlos periódicamente a la alta dirección." },
  { id: 8, principio: "RATIONALES", tactica: "Documentación", pregunta: "¿Se justifica documentalmente todo valor de entrada en los modelos de riesgo utilizados?", accion: "Documentar la justificación cuantitativa o cualitativa de cada valor utilizado en evaluaciones de riesgo." },
  { id: 9, principio: "RATIONALES", tactica: "Documentación", pregunta: "¿Se justifican los criterios utilizados para la implementación de las operaciones DevPrivOps y DevSecOps?", accion: "Mantener registro de decisiones con la justificación de cada medida adoptada o descartada." },
  { id: 10, principio: "CONFORMIDAD", tactica: "Implementación real", pregunta: "¿La gestión de riesgos de protección de datos se implementa en la práctica y no solo documentalmente?", accion: "Verificar con pruebas que los controles documentados estén efectivamente operando." },
  { id: 11, principio: "CONFORMIDAD", tactica: "Escenarios", pregunta: "¿Se aplican las operaciones DevPrivOps y DevSecOps en diversos escenarios de riesgo reales?", accion: "Realizar ejercicios de simulación y pruebas de los controles en escenarios realistas." },
  { id: 12, principio: "AUDITORÍAS", tactica: "Eficacia", pregunta: "¿Se auditan las operaciones DevPrivOps y DevSecOps en función de su eficacia y eficiencia?", accion: "Programar auditorías internas y/o externas de privacidad y seguridad al menos anualmente." },
  { id: 13, principio: "AUDITORÍAS", tactica: "Permeabilidad", pregunta: "¿Se analiza la permeabilidad de cada operación evaluando sus probabilidades reales de cumplimiento?", accion: "Evaluar el cumplimiento real (no solo documental) de cada control implementado." },
  { id: 14, principio: "AUDITORÍAS", tactica: "ROSI", pregunta: "¿Se evalúa el retorno a la inversión en seguridad (ROSI) de los controles implementados?", accion: "Calcular y documentar el ROSI para justificar inversiones en protección de datos." },
  { id: 15, principio: "PREVENIR", tactica: "Confidencialidad", pregunta: "¿Se gestionan controles para prevenir vulneraciones a la confidencialidad de datos personales?", accion: "Implementar DLP, cifrado y controles de acceso para prevenir fugas de información." },
  { id: 16, principio: "PREVENIR", tactica: "Integridad", pregunta: "¿Se gestionan controles para prevenir vulneraciones a la integridad de datos personales?", accion: "Implementar controles de integridad (hashes, firmas digitales, validaciones)." },
  { id: 17, principio: "PREVENIR", tactica: "Disponibilidad", pregunta: "¿Se gestionan controles para prevenir vulneraciones a la disponibilidad de datos personales?", accion: "Implementar redundancia, backups y planes de continuidad para sistemas con datos personales." },
  { id: 18, principio: "PREVENIR", tactica: "Reducción prob.", pregunta: "¿Se mide y gestiona la reducción de probabilidad de ocurrencia de vulneraciones de seguridad?", accion: "Establecer indicadores de reducción de riesgo y monitorear su evolución." },
];

export type EjeKey = "priv" | "sec" | "risk";

export const EJES: Array<{ key: EjeKey; label: string; data: ControlItem[] }> = [
  { key: "priv", label: "DevPrivOps — Privacidad", data: PRIVOPS },
  { key: "sec",  label: "DevSecOps — Seguridad",  data: SECOPS  },
  { key: "risk", label: "DevRiskOps — Riesgos",   data: RISKOPS },
];
