export type OrgUnitStatus = "Activa" | "Inactiva";
export type OrgUnitType =
  | "Institucion"
  | "Macroproceso"
  | "Organo"
  | "Direccion"
  | "Subdireccion"
  | "Comite"
  | "Entidad vinculada";

export type OrgUnit = {
  id: string;
  nombre: string;
  sigla?: string;
  tipo: OrgUnitType;
  parentId?: string;
  status: OrgUnitStatus;
  ownerRole: string;
};

const orgUnits: OrgUnit[] = [
  {
    id: "iess",
    nombre: "Instituto Ecuatoriano de Seguridad Social",
    sigla: "IESS",
    tipo: "Institucion",
    status: "Activa",
    ownerRole: "Direccion General",
  },
  {
    id: "org-gobernantes",
    nombre: "Organos gobernantes",
    tipo: "Macroproceso",
    parentId: "iess",
    status: "Activa",
    ownerRole: "Consejo Directivo",
  },
  {
    id: "consejo-directivo",
    nombre: "Consejo Directivo",
    sigla: "CD",
    tipo: "Organo",
    parentId: "org-gobernantes",
    status: "Activa",
    ownerRole: "Maximo organo de gobierno",
  },
  {
    id: "presidencia-cd",
    nombre: "Presidencia del Consejo Directivo",
    tipo: "Organo",
    parentId: "org-gobernantes",
    status: "Activa",
    ownerRole: "Presidencia institucional",
  },
  {
    id: "direccion-general",
    nombre: "Direccion General",
    sigla: "DG",
    tipo: "Direccion",
    parentId: "org-gobernantes",
    status: "Activa",
    ownerRole: "Direccion General",
  },
  {
    id: "asesoria-cd",
    nombre: "Procesos adjetivos de asesoria dependientes del Consejo Directivo",
    tipo: "Macroproceso",
    parentId: "iess",
    status: "Activa",
    ownerRole: "Consejo Directivo",
  },
  {
    id: "comision-apelaciones",
    nombre: "Comision Nacional de Apelaciones",
    tipo: "Organo",
    parentId: "asesoria-cd",
    status: "Activa",
    ownerRole: "Consejo Directivo",
  },
  {
    id: "prosecretaria-cd",
    nombre: "Prosecretaria del Consejo Directivo",
    tipo: "Organo",
    parentId: "asesoria-cd",
    status: "Activa",
    ownerRole: "Consejo Directivo",
  },
  {
    id: "daie",
    nombre: "Direccion Actuarial, de Investigacion y Estadistica",
    sigla: "DAIE",
    tipo: "Direccion",
    parentId: "asesoria-cd",
    status: "Activa",
    ownerRole: "Director actuarial",
  },
  {
    id: "dnsac",
    nombre: "Direccion Nacional de Servicios de Atencion al Ciudadano",
    sigla: "DNSAC",
    tipo: "Direccion",
    parentId: "asesoria-cd",
    status: "Activa",
    ownerRole: "Director nacional de atencion al ciudadano",
  },
  {
    id: "dncs",
    nombre: "Direccion Nacional de Comunicacion Social",
    sigla: "DNCS",
    tipo: "Direccion",
    parentId: "asesoria-cd",
    status: "Activa",
    ownerRole: "Director nacional de comunicacion",
  },
  {
    id: "dnri",
    nombre: "Direccion Nacional de Riesgos Institucionales",
    sigla: "DNRI",
    tipo: "Direccion",
    parentId: "asesoria-cd",
    status: "Activa",
    ownerRole: "Director nacional de riesgos",
  },
  {
    id: "dnri-financiero",
    nombre: "Subdireccion Nacional de Riesgo Financiero",
    tipo: "Subdireccion",
    parentId: "dnri",
    status: "Activa",
    ownerRole: "Subdirector nacional de riesgo financiero",
  },
  {
    id: "dnri-operativo",
    nombre: "Subdireccion Nacional de Riesgo Operativo",
    tipo: "Subdireccion",
    parentId: "dnri",
    status: "Activa",
    ownerRole: "Subdirector nacional de riesgo operativo",
  },
  {
    id: "dnsi",
    nombre: "Direccion Nacional de Seguridad de la Informacion",
    sigla: "DNSI",
    tipo: "Direccion",
    parentId: "asesoria-cd",
    status: "Activa",
    ownerRole: "Director nacional de seguridad de la informacion",
  },
  {
    id: "asesoria-dg",
    nombre: "Procesos adjetivos de asesoria dependientes de la Direccion General",
    tipo: "Macroproceso",
    parentId: "iess",
    status: "Activa",
    ownerRole: "Direccion General",
  },
  {
    id: "auditoria-interna",
    nombre: "Auditoria Interna",
    sigla: "AI",
    tipo: "Organo",
    parentId: "asesoria-dg",
    status: "Activa",
    ownerRole: "Auditor interno",
  },
  {
    id: "pg",
    nombre: "Procuraduria General",
    sigla: "PG",
    tipo: "Direccion",
    parentId: "asesoria-dg",
    status: "Activa",
    ownerRole: "Procurador General",
  },
  {
    id: "pg-patrocinio",
    nombre: "Subdireccion Nacional de Patrocinio",
    tipo: "Subdireccion",
    parentId: "pg",
    status: "Activa",
    ownerRole: "Subdirector nacional de patrocinio",
  },
  {
    id: "pg-legal",
    nombre: "Subdireccion Nacional de Asesoria Legal",
    tipo: "Subdireccion",
    parentId: "pg",
    status: "Activa",
    ownerRole: "Subdirector nacional de asesoria legal",
  },
  {
    id: "dnpl",
    nombre: "Direccion Nacional de Planificacion",
    sigla: "DNPL",
    tipo: "Direccion",
    parentId: "asesoria-dg",
    status: "Activa",
    ownerRole: "Director nacional de planificacion",
  },
  {
    id: "dnpr",
    nombre: "Direccion Nacional de Procesos",
    sigla: "DNPR",
    tipo: "Direccion",
    parentId: "asesoria-dg",
    status: "Activa",
    ownerRole: "Director nacional de procesos",
  },
  {
    id: "subdireccion-general",
    nombre: "Subdireccion General",
    tipo: "Macroproceso",
    parentId: "iess",
    status: "Activa",
    ownerRole: "Subdirector General",
  },
  {
    id: "subdireccion-general-main",
    nombre: "Subdireccion General",
    tipo: "Subdireccion",
    parentId: "subdireccion-general",
    status: "Activa",
    ownerRole: "Subdirector General",
  },
  {
    id: "subdir-control-tecnico-general",
    nombre: "Subdireccion de Control Tecnico",
    tipo: "Subdireccion",
    parentId: "subdireccion-general",
    status: "Activa",
    ownerRole: "Subdirector de control tecnico",
  },
  {
    id: "subdir-seguimiento",
    nombre: "Subdireccion de Seguimiento y Evaluacion",
    tipo: "Subdireccion",
    parentId: "subdireccion-general",
    status: "Activa",
    ownerRole: "Subdirector de seguimiento y evaluacion",
  },
  {
    id: "subdir-campesino-control",
    nombre: "Subdireccion de Gestion y Control del Seguro Social Campesino",
    tipo: "Subdireccion",
    parentId: "subdireccion-general",
    status: "Activa",
    ownerRole: "Subdirector de gestion y control campesino",
  },
  {
    id: "subdir-riesgos-control",
    nombre: "Subdireccion de Gestion y Control del Seguro de Riesgos del Trabajo",
    tipo: "Subdireccion",
    parentId: "subdireccion-general",
    status: "Activa",
    ownerRole: "Subdirector de gestion y control de riesgos del trabajo",
  },
  {
    id: "subdir-pensiones-control",
    nombre: "Subdireccion de Gestion y Control del Sistema de Pensiones",
    tipo: "Subdireccion",
    parentId: "subdireccion-general",
    status: "Activa",
    ownerRole: "Subdirector de gestion y control del sistema de pensiones",
  },
  {
    id: "sustantivos",
    nombre: "Procesos sustantivos",
    tipo: "Macroproceso",
    parentId: "iess",
    status: "Activa",
    ownerRole: "Direccion General",
  },
  {
    id: "dnac",
    nombre: "Direccion Nacional de Afiliacion y Cobertura",
    sigla: "DNAC",
    tipo: "Direccion",
    parentId: "sustantivos",
    status: "Activa",
    ownerRole: "Director nacional de afiliacion y cobertura",
  },
  {
    id: "dnac-afiliacion",
    nombre: "Subdireccion de Afiliacion, Cobertura y Gestion de la Informacion",
    tipo: "Subdireccion",
    parentId: "dnac",
    status: "Activa",
    ownerRole: "Subdirector de afiliacion y cobertura",
  },
  {
    id: "dnac-control-tecnico",
    nombre: "Subdireccion de Control Tecnico",
    tipo: "Subdireccion",
    parentId: "dnac",
    status: "Activa",
    ownerRole: "Subdirector de control tecnico",
  },
  {
    id: "dnrgc",
    nombre: "Direccion Nacional de Recaudacion y Gestion de Cartera",
    sigla: "DNRGC",
    tipo: "Direccion",
    parentId: "sustantivos",
    status: "Activa",
    ownerRole: "Director nacional de recaudacion y cartera",
  },
  {
    id: "dnrgc-recaudacion",
    nombre: "Subdireccion de Recaudacion",
    tipo: "Subdireccion",
    parentId: "dnrgc",
    status: "Activa",
    ownerRole: "Subdirector de recaudacion",
  },
  {
    id: "dnrgc-cartera",
    nombre: "Subdireccion de Gestion de Cartera",
    tipo: "Subdireccion",
    parentId: "dnrgc",
    status: "Activa",
    ownerRole: "Subdirector de gestion de cartera",
  },
  {
    id: "dsgsif",
    nombre: "Direccion del Seguro General de Salud Individual y Familiar",
    sigla: "DSGSIF",
    tipo: "Direccion",
    parentId: "sustantivos",
    status: "Activa",
    ownerRole: "Director del seguro de salud",
  },
  {
    id: "dsgsif-aseguramiento",
    nombre: "Subdireccion de Aseguramiento del Seguro de Salud",
    tipo: "Subdireccion",
    parentId: "dsgsif",
    status: "Activa",
    ownerRole: "Subdirector de aseguramiento",
  },
  {
    id: "dsgsif-provision",
    nombre: "Subdireccion de Provision de Servicios de Salud",
    tipo: "Subdireccion",
    parentId: "dsgsif",
    status: "Activa",
    ownerRole: "Subdirector de provision de servicios",
  },
  {
    id: "dsgsif-calidad",
    nombre: "Subdireccion de Garantia de la Calidad de los Servicios del Seguro de Salud",
    tipo: "Subdireccion",
    parentId: "dsgsif",
    status: "Activa",
    ownerRole: "Subdirector de garantia de la calidad",
  },
  {
    id: "dsgsif-info",
    nombre: "Subdireccion de Vigilancia y Gestion de la Informacion del Seguro de Salud",
    tipo: "Subdireccion",
    parentId: "dsgsif",
    status: "Activa",
    ownerRole: "Subdirector de vigilancia y gestion de la informacion",
  },
  {
    id: "dsgsif-financiera",
    nombre: "Subdireccion Financiera del Seguro de Salud",
    tipo: "Subdireccion",
    parentId: "dsgsif",
    status: "Activa",
    ownerRole: "Subdirector financiero del seguro de salud",
  },
  {
    id: "dssc",
    nombre: "Direccion del Seguro Social Campesino",
    sigla: "DSSC",
    tipo: "Direccion",
    parentId: "sustantivos",
    status: "Activa",
    ownerRole: "Director del seguro social campesino",
  },
  {
    id: "dssc-control",
    nombre: "Subdireccion de Gestion y Control del Seguro Social Campesino",
    tipo: "Subdireccion",
    parentId: "dssc",
    status: "Activa",
    ownerRole: "Subdirector de gestion y control campesino",
  },
  {
    id: "dssc-prestaciones",
    nombre: "Subdireccion de Prestaciones de Salud del Seguro Social Campesino",
    tipo: "Subdireccion",
    parentId: "dssc",
    status: "Activa",
    ownerRole: "Subdirector de prestaciones de salud",
  },
  {
    id: "dssc-financiera",
    nombre: "Subdireccion Financiera del Seguro Social Campesino",
    tipo: "Subdireccion",
    parentId: "dssc",
    status: "Activa",
    ownerRole: "Subdirector financiero del seguro social campesino",
  },
  {
    id: "dsgrt",
    nombre: "Direccion del Seguro General de Riesgos del Trabajo",
    sigla: "DSGRT",
    tipo: "Direccion",
    parentId: "sustantivos",
    status: "Activa",
    ownerRole: "Director del seguro de riesgos del trabajo",
  },
  {
    id: "dsgrt-control",
    nombre: "Subdireccion de Gestion y Control del Seguro de Riesgos del Trabajo",
    tipo: "Subdireccion",
    parentId: "dsgrt",
    status: "Activa",
    ownerRole: "Subdirector de gestion y control del seguro de riesgos",
  },
  {
    id: "dsgrt-financiera",
    nombre: "Subdireccion Financiera del Seguro de Riesgos del Trabajo",
    tipo: "Subdireccion",
    parentId: "dsgrt",
    status: "Activa",
    ownerRole: "Subdirector financiero del seguro de riesgos",
  },
  {
    id: "dsp",
    nombre: "Direccion del Sistema de Pensiones",
    sigla: "DSP",
    tipo: "Direccion",
    parentId: "sustantivos",
    status: "Activa",
    ownerRole: "Director del sistema de pensiones",
  },
  {
    id: "dsp-control",
    nombre: "Subdireccion de Gestion y Control del Sistema de Pensiones",
    tipo: "Subdireccion",
    parentId: "dsp",
    status: "Activa",
    ownerRole: "Subdirector de gestion y control del sistema de pensiones",
  },
  {
    id: "dsp-financiera",
    nombre: "Subdireccion Financiera del Sistema de Pensiones",
    tipo: "Subdireccion",
    parentId: "dsp",
    status: "Activa",
    ownerRole: "Subdirector financiero del sistema de pensiones",
  },
  {
    id: "dnftsd",
    nombre: "Direccion Nacional de Fondos de Terceros y Seguro de Desempleo",
    sigla: "DNFTSD",
    tipo: "Direccion",
    parentId: "sustantivos",
    status: "Activa",
    ownerRole: "Director nacional de fondos de terceros y desempleo",
  },
  {
    id: "dnftsd-desempleo",
    nombre: "Subdireccion del Seguro de Desempleo",
    tipo: "Subdireccion",
    parentId: "dnftsd",
    status: "Activa",
    ownerRole: "Subdirector del seguro de desempleo",
  },
  {
    id: "dnftsd-fondos",
    nombre: "Subdireccion de Fondos de Terceros",
    tipo: "Subdireccion",
    parentId: "dnftsd",
    status: "Activa",
    ownerRole: "Subdirector de fondos de terceros",
  },
  {
    id: "apoyo",
    nombre: "Procesos adjetivos de apoyo",
    tipo: "Macroproceso",
    parentId: "iess",
    status: "Activa",
    ownerRole: "Direccion General",
  },
  {
    id: "dngf",
    nombre: "Direccion Nacional de Gestion Financiera",
    sigla: "DNGF",
    tipo: "Direccion",
    parentId: "apoyo",
    status: "Activa",
    ownerRole: "Director nacional de gestion financiera",
  },
  {
    id: "dngf-presupuesto",
    nombre: "Subdireccion de Consolidacion Presupuestaria",
    tipo: "Subdireccion",
    parentId: "dngf",
    status: "Activa",
    ownerRole: "Subdirector de consolidacion presupuestaria",
  },
  {
    id: "dngf-contabilidad",
    nombre: "Subdireccion de Contabilidad",
    tipo: "Subdireccion",
    parentId: "dngf",
    status: "Activa",
    ownerRole: "Subdirector de contabilidad",
  },
  {
    id: "dngf-pagos",
    nombre: "Subdireccion de Transferencias y Pagos",
    tipo: "Subdireccion",
    parentId: "dngf",
    status: "Activa",
    ownerRole: "Subdirector de transferencias y pagos",
  },
  {
    id: "dngf-rentabilidad",
    nombre: "Subdireccion de Supervision de la Rentabilidad de los Fondos Previsionales",
    tipo: "Subdireccion",
    parentId: "dngf",
    status: "Activa",
    ownerRole: "Subdirector de supervision de rentabilidad",
  },
  {
    id: "dnti",
    nombre: "Direccion Nacional de Tecnologias de la Informacion",
    sigla: "DNTI",
    tipo: "Direccion",
    parentId: "apoyo",
    status: "Activa",
    ownerRole: "Director nacional de tecnologias de la informacion",
  },
  {
    id: "dnti-infra",
    nombre: "Subdireccion de Infraestructura de Tecnologias de la Informacion",
    tipo: "Subdireccion",
    parentId: "dnti",
    status: "Activa",
    ownerRole: "Subdirector de infraestructura TI",
  },
  {
    id: "dnti-desarrollo",
    nombre: "Subdireccion de Desarrollo Informatico",
    tipo: "Subdireccion",
    parentId: "dnti",
    status: "Activa",
    ownerRole: "Subdirector de desarrollo informatico",
  },
  {
    id: "dnti-arquitectura",
    nombre: "Subdireccion de Arquitectura y Soluciones",
    tipo: "Subdireccion",
    parentId: "dnti",
    status: "Activa",
    ownerRole: "Subdirector de arquitectura y soluciones",
  },
  {
    id: "dnti-seguridad",
    nombre: "Subdireccion de Seguridad Informatica",
    tipo: "Subdireccion",
    parentId: "dnti",
    status: "Activa",
    ownerRole: "Subdirector de seguridad informatica",
  },
  {
    id: "dnsc",
    nombre: "Direccion Nacional de Servicios Corporativos",
    sigla: "DNSC",
    tipo: "Direccion",
    parentId: "apoyo",
    status: "Activa",
    ownerRole: "Director nacional de servicios corporativos",
  },
  {
    id: "dnsc-administrativa",
    nombre: "Subdireccion Administrativa",
    tipo: "Subdireccion",
    parentId: "dnsc",
    status: "Activa",
    ownerRole: "Subdirector administrativo",
  },
  {
    id: "dnsc-compras",
    nombre: "Subdireccion de Compras Publicas",
    tipo: "Subdireccion",
    parentId: "dnsc",
    status: "Activa",
    ownerRole: "Subdirector de compras publicas",
  },
  {
    id: "dnsc-infra",
    nombre: "Subdireccion de Infraestructura y Equipamiento",
    tipo: "Subdireccion",
    parentId: "dnsc",
    status: "Activa",
    ownerRole: "Subdirector de infraestructura y equipamiento",
  },
  {
    id: "dnsc-th",
    nombre: "Subdireccion de Gestion de Talento Humano",
    tipo: "Subdireccion",
    parentId: "dnsc",
    status: "Activa",
    ownerRole: "Subdirector de talento humano",
  },
  {
    id: "dnsc-documental",
    nombre: "Subdireccion de Gestion Documental",
    tipo: "Subdireccion",
    parentId: "dnsc",
    status: "Activa",
    ownerRole: "Subdirector de gestion documental",
  },
  {
    id: "dncri",
    nombre: "Direccion Nacional de Cooperacion y Relaciones Internacionales",
    sigla: "DNCRI",
    tipo: "Direccion",
    parentId: "apoyo",
    status: "Activa",
    ownerRole: "Director nacional de cooperacion y relaciones internacionales",
  },
  {
    id: "comites",
    nombre: "Organos colegiados y comites",
    tipo: "Macroproceso",
    parentId: "iess",
    status: "Activa",
    ownerRole: "Direccion General",
  },
  {
    id: "comite-riesgos",
    nombre: "Comite de Administracion Integral de Riesgos",
    tipo: "Comite",
    parentId: "comites",
    status: "Activa",
    ownerRole: "Comite institucional de riesgos",
  },
  {
    id: "comite-seguridad",
    nombre: "Comite de Seguridad de la Informacion",
    tipo: "Comite",
    parentId: "comites",
    status: "Activa",
    ownerRole: "Comite institucional de seguridad",
  },
  {
    id: "comite-incapacidades",
    nombre: "Comite de Evaluacion de Incapacidades y Responsabilidad Patronal",
    tipo: "Comite",
    parentId: "comites",
    status: "Activa",
    ownerRole: "Comite de evaluacion",
  },
  {
    id: "comite-valuador",
    nombre: "Comite Nacional Valuador",
    tipo: "Comite",
    parentId: "comites",
    status: "Activa",
    ownerRole: "Comite valuador",
  },
  {
    id: "comite-informatico",
    nombre: "Comite Informatico",
    tipo: "Comite",
    parentId: "comites",
    status: "Activa",
    ownerRole: "Comite informatico",
  },
  {
    id: "entidades-vinculadas",
    nombre: "Entidades vinculadas",
    tipo: "Macroproceso",
    parentId: "iess",
    status: "Activa",
    ownerRole: "Direccion General",
  },
  {
    id: "biess",
    nombre: "BIESS",
    sigla: "BIESS",
    tipo: "Entidad vinculada",
    parentId: "entidades-vinculadas",
    status: "Activa",
    ownerRole: "Entidad vinculada",
  },
];

export function getOrganizationUnits() {
  return orgUnits;
}
